name: Patch

on:
  workflow_dispatch:
    inputs:
      releaseVersion:
        description: Release version (vX.X)
        required: true
        type: string

jobs:
  run-patch:
    uses: powsybl/github-ci/.github/workflows/patch-frontend-app-generic.yml@b3ea78542917e45f79333e9222154b48f6639bf6
    with:
      releaseVersion: ${{ github.event.inputs.releaseVersion }}
      dockerImage: docker.io/gridsuite/gridadmin-app
      dockerUsername: gridsuiteci
      githubappId: ${{ vars.GRIDSUITE_ACTIONS_APPID }}
    secrets:
      githubappPrivateKey: ${{ secrets.GRIDSUITE_ACTIONS_SECRET }}
      docker-token: ${{ secrets.DOCKERHUB_TOKEN }}
      sonar-token: ${{ secrets.SONAR_TOKEN }}
